[project]
name = "gpuocean"
version = "1.4.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13.0"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "nbdime",
    "mpi4py",
    "netcdf4",
    "requests",
    "pyproj",
    "pytools",
    "seawater",
    "gitpython",
    "scikit-image",
    "tqdm",
]

[project.optional-dependencies]
gpu = [
    "hip-python~=7.0.0",
    "cupy-rocm-7-0~=14.0.1",
]
lumi = [
    "hip-python~=6.4.4",
    "cupy~=14.0.1",
]

[tool.uv]
no-binary-package = ["mpi4py", "netcdf4"]
conflicts = [
    [
        { extra = "gpu" },
        { extra = "lumi" },
    ]
]

[tool.uv.extra-build-dependencies]
netcdf4 = [{requirement = "mpi4py", match-runtime = true}]

[tool.uv.sources]
hip-python = { index = "hip" }

[[tool.uv.index]]
name = "hip"
url = "https://test.pypi.org/simple/"
explicit = true

[build-system]
requires = ["uv_build>=0.9.23,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    {include-group = "test"},
    {include-group = "jupyter"},
    "pydevd-pycharm~=253.29346.142",
    "scipy-stubs~=1.15.3",
]
test = [
    "pytest",
    "unittest-xml-reporting",
]
jupyter = [
    "notebook>=7.4.7",
]

